---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 7
num_rounds: 400

batch_size: 32
local_epochs: 10

epochs_min: 5 # minimum number of epochs
epochs_max: 20 # maximum number of epochs
batch_size_min: 32 # minimum batch size
batch_size_max: 128 # maximum batch size
fraction_samples_min: 0.1 # minimum fraction of samples
fraction_samples_max: 0.8 # maximum fraction of samples

local_epochs_default: 10 # number of local epochs
batch_size_default: 32 # batch size
fraction_samples_default: 0.8 

seed: 39

client_resources:
  num_cpus: 1
  num_gpus: 0

dataset:
  dataset: "TACO"
  num_classes: 2

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${optimizer}_${dataset.dataset}_a${alpha}_beta${strategy.decay_coefficient}
